services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lab_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    hostname: jupyter
    container_name: jupyter
    working_dir: /app
    command: start-notebook.py --IdentityProvider.token='' --ServerApp.password=''
    ports:
      - "8888:8888"
    volumes:
      - ./datasets:/app/datasets
      - ./notebooks:/app/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=lab_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
